name: mascheya

dependencies:
  - base >=4.22.0.0
  - containers
  - mtl

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - mascheya

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - mascheya
      - hspec

ghc-options:
  - -Wall